### ISSUE TITLE
Seems to be broken in Firefox

### ISSUE THREAD

**Issue by whereswaldon** [orbitdb/orbit-web#8]
I went to https://orbit.chat in firefox, and it creates the login screen fine. When I supply a username and hit enter, it says "loading" forever and dumps these errors in the console. This is on Ubuntu 16.04 with Firefox 53.0.

```
isElectron: false  orbit.chat:60:5
TypeError: asm.js type error: double is not a subtype of int  app.js:87:547
```

**Comment by r0kk3rz** [comment]
Works ok for me, I had an issue with the user-agent not being set properly in my browser (not sure why) but now it loads

**Comment by haadcode** [comment]
Works here too but a new bug that has appeared (along with new versions of FF since Apr) is that it crashes FF and hangs the whole browser after a while. Orbit's code hasn't been updated, so something has in FF that's causing this new behaviour.

If anyone has more info and/or details to this, would be great to get your input!

**Comment by haadcode** [comment]
That said, the crashing/hanging seems to also happen in Chrome.

**Comment by noxarivis** [comment]
I sometimes have similar problems

**Comment by noxarivis** [comment]
ECMAScript 6?

**Comment by bj0** [comment]
I see this issue when using a Private Browsing Window in firefox, but not if I just use a normal window.

**Comment by notramo** [comment]
@haadcode Does Firefox disable something in private mode?
Is there any opportunity to make it work without disabling private mode?

**Comment by latenssi** [comment]
Closing this as this has been fixed.
